# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'TabbarSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TabbarSample
     pod 'Firebase/Auth'
     pod 'NVActivityIndicatorView'

     pod 'Firebase/Database'
     pod 'FSCalendar'
  target 'TabbarSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TabbarSampleUITests' do
    # Pods for testing
  end

end
