# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '02AlertView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 02AlertView
  pod 'Moya', '~> 14.0'
  pod 'RealmSwift'   # https://github.com/realm/realm-cocoa
end
